In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
df = pd.read_csv('final_data.csv')

In [3]:
df

Unnamed: 0        DATE  start_station_id  hour_of_day  COUNT  \
0                 0  2015-04-23            3004.0           10      5   
1                 1  2015-04-23            3004.0           12      3   
2                 2  2015-04-23            3004.0           13      2   
3                 3  2015-04-23            3004.0           14      1   
4                 4  2015-04-23            3004.0           15      5   
...             ...         ...               ...          ...    ...   
1444211     1444211  2019-09-30            3210.0            9      3   
1444212     1444212  2019-09-30            3210.0           10      1   
1444213     1444213  2019-09-30            3210.0           11      1   
1444214     1444214  2019-09-30            3210.0           12      1   
1444215     1444215  2019-09-30            3210.0           17      4   

         AVG_WND_SPEED  PRCP  SNOW  SNOW_DEPTH  TAVG  TMAX  TMIN  FOG  \
0                15.21   0.0   0.0         0.0  48.0    52    43  0.0   
1                15.21   0.0   0.0         0.0  48.0    52    43  0.0   
2                15.21   0.0   0.0         0.0  48.0    52    43  0.0   
3                15.21   0.0   0.0         0.0  48.0    52    43  0.0   
4                15.21   0.0   0.0         0.0  48.0    52    43  0.0   
...                ...   ...   ...         ...   ...   ...   ...  ...   
1444211           7.61   0.0   0.0         0.0  69.0    75    62  0.0   
1444212           7.61   0.0   0.0         0.0  69.0    75    62  0.0   
1444213           7.61   0.0   0.0         0.0  69.0    75    62  0.0   
1444214           7.61   0.0   0.0         0.0  69.0    75    62  0.0   
1444215           7.61   0.0   0.0         0.0  69.0    75    62  0.0   

         THUNDER  SLEET_OR_HAIL  month  year  
0            0.0            0.0      4  2015  
1            0.0            0.0      4  2015  
2            0.0            0.0      4  2015  
3            0.0            0.0      4  2015  
4            0.0            0.0      4  2015  
...          ...            ...    ...   ...  
1444211      0.0            0.0      9  2019  
1444212      0.0            0.0      9  2019  
1444213      0.0            0.0      9  2019  
1444214      0.0            0.0      9  2019  
1444215      0.0            0.0      9  2019  

[1444216 rows x 17 columns]

In [4]:
df[df.isna().any(axis=1)]

Unnamed: 0        DATE  start_station_id  hour_of_day  COUNT  \
177784      177784  2016-01-01            3004.0           13      2   
177785      177785  2016-01-01            3004.0           14      1   
177786      177786  2016-01-01            3004.0           15      2   
177787      177787  2016-01-01            3004.0           17      1   
177788      177788  2016-01-01            3004.0           18      1   
...            ...         ...               ...          ...    ...   
188920      188920  2016-01-31            3086.0           16      1   
188921      188921  2016-01-31            3086.0           17      1   
188922      188922  2016-01-31            3086.0           18      2   
188923      188923  2016-01-31            3088.0           14      2   
188924      188924  2016-01-31            3088.0           15      1   

        AVG_WND_SPEED  PRCP  SNOW  SNOW_DEPTH  TAVG  TMAX  TMIN  FOG  THUNDER  \
177784          11.63   0.0   0.0         0.0   NaN    43    34  0.0      0.0   
177785          11.63   0.0   0.0         0.0   NaN    43    34  0.0      0.0   
177786          11.63   0.0   0.0         0.0   NaN    43    34  0.0      0.0   
177787          11.63   0.0   0.0         0.0   NaN    43    34  0.0      0.0   
177788          11.63   0.0   0.0         0.0   NaN    43    34  0.0      0.0   
...               ...   ...   ...         ...   ...   ...   ...  ...      ...   
188920           5.37   0.0   0.0         3.9   NaN    58    30  0.0      0.0   
188921           5.37   0.0   0.0         3.9   NaN    58    30  0.0      0.0   
188922           5.37   0.0   0.0         3.9   NaN    58    30  0.0      0.0   
188923           5.37   0.0   0.0         3.9   NaN    58    30  0.0      0.0   
188924           5.37   0.0   0.0         3.9   NaN    58    30  0.0      0.0   

        SLEET_OR_HAIL  month  year  
177784            0.0      1  2016  
177785            0.0      1  2016  
177786            0.0      1  2016  
177787            0.0      1  2016  
177788            0.0      1  2016  
...               ...    ...   ...  
188920            0.0      1  2016  
188921            0.0      1  2016  
188922            0.0      1  2016  
188923            0.0      1  2016  
188924            0.0      1  2016  

[11141 rows x 17 columns]

In [7]:
df[df['TAVG'].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, DATE, start_station_id, hour_of_day, COUNT, AVG_WND_SPEED, PRCP, SNOW, SNOW_DEPTH, TAVG, TMAX, TMIN, FOG, THUNDER, SLEET_OR_HAIL, month, year]
Index: []

In [6]:
df['TAVG'] = df.apply(lambda row: ((row['TMAX']+row['TMIN'])/2) if np.isnan(row['TAVG']) else row['TAVG'],axis=1)

In [32]:
df

DATE  start_station_id  hour_of_day  COUNT  AVG_WND_SPEED  \
0        2015-04-23            3004.0           10      5          15.21   
1        2015-04-23            3004.0           12      3          15.21   
2        2015-04-23            3004.0           13      2          15.21   
3        2015-04-23            3004.0           14      1          15.21   
4        2015-04-23            3004.0           15      5          15.21   
...             ...               ...          ...    ...            ...   
1444211  2019-09-30            3210.0            9      3           7.61   
1444212  2019-09-30            3210.0           10      1           7.61   
1444213  2019-09-30            3210.0           11      1           7.61   
1444214  2019-09-30            3210.0           12      1           7.61   
1444215  2019-09-30            3210.0           17      4           7.61   

         PRCP  SNOW  SNOW_DEPTH  TAVG  TMAX  TMIN  FOG  THUNDER  \
0         0.0   0.0         0.0  48.0    52    43  0.0      0.0   
1         0.0   0.0         0.0  48.0    52    43  0.0      0.0   
2         0.0   0.0         0.0  48.0    52    43  0.0      0.0   
3         0.0   0.0         0.0  48.0    52    43  0.0      0.0   
4         0.0   0.0         0.0  48.0    52    43  0.0      0.0   
...       ...   ...         ...   ...   ...   ...  ...      ...   
1444211   0.0   0.0         0.0  69.0    75    62  0.0      0.0   
1444212   0.0   0.0         0.0  69.0    75    62  0.0      0.0   
1444213   0.0   0.0         0.0  69.0    75    62  0.0      0.0   
1444214   0.0   0.0         0.0  69.0    75    62  0.0      0.0   
1444215   0.0   0.0         0.0  69.0    75    62  0.0      0.0   

         SLEET_OR_HAIL  month  year  
0                  0.0      4  2015  
1                  0.0      4  2015  
2                  0.0      4  2015  
3                  0.0      4  2015  
4                  0.0      4  2015  
...                ...    ...   ...  
1444211            0.0      9  2019  
1444212            0.0      9  2019  
1444213            0.0      9  2019  
1444214            0.0      9  2019  
1444215            0.0      9  2019  

[1444216 rows x 16 columns]

In [8]:
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [Unnamed: 0, DATE, start_station_id, hour_of_day, COUNT, AVG_WND_SPEED, PRCP, SNOW, SNOW_DEPTH, TAVG, TMAX, TMIN, FOG, THUNDER, SLEET_OR_HAIL, month, year]
Index: []

In [9]:
df = df.drop(['Unnamed: 0'], axis=1)

In [10]:
df.columns.values

array(['DATE', 'start_station_id', 'hour_of_day', 'COUNT',
       'AVG_WND_SPEED', 'PRCP', 'SNOW', 'SNOW_DEPTH', 'TAVG', 'TMAX',
       'TMIN', 'FOG', 'THUNDER', 'SLEET_OR_HAIL', 'month', 'year'],
      dtype=object)

In [11]:
df.to_csv("final_data_2.csv")

In [36]:
X = df[['start_station_id', 'hour_of_day', 'AVG_WND_SPEED', 'PRCP', 'SNOW', 'SNOW_DEPTH', 'TAVG', 'TMAX', 'TMIN', 'FOG', 'THUNDER', 'SLEET_OR_HAIL', 'month', 'year']]
y = df['COUNT']

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [11]:
from sklearn.neural_network import MLPRegressor,MLPClassifier

In [45]:
mlp = MLPClassifier(hidden_layer_sizes=(5,5), verbose=3)

In [46]:
mlp.fit(X_train,y_train)

Iteration 1, loss = 1.79167245
Iteration 2, loss = 1.45893714
Iteration 3, loss = 1.45722796
Iteration 4, loss = 1.45598925
Iteration 5, loss = 1.45499267
Iteration 6, loss = 1.45395484
Iteration 7, loss = 1.45243746
Iteration 8, loss = 1.44918986
Iteration 9, loss = 1.44595335
Iteration 10, loss = 1.44366823
Iteration 11, loss = 1.43981285
Iteration 12, loss = 1.43924099
Iteration 13, loss = 1.43875277
Iteration 14, loss = 1.43849801
Iteration 15, loss = 1.43829583
Iteration 16, loss = 1.43820892
Iteration 17, loss = 1.43789245
Iteration 18, loss = 1.43800996
Iteration 19, loss = 1.43789496
Iteration 20, loss = 1.43754706
Iteration 21, loss = 1.43759740
Iteration 22, loss = 1.43759369
Iteration 23, loss = 1.43751020
Iteration 24, loss = 1.43760957
Iteration 25, loss = 1.43743637
Iteration 26, loss = 1.43740419
Iteration 27, loss = 1.43734547
Iteration 28, loss = 1.43709565
Iteration 29, loss = 1.43727206
Iteration 30, loss = 1.43728615
Iteration 31, loss = 1.43729403
Iteration 32, los

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(5, 5), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=3, warm_start=False)

In [47]:
import pickle
filename = 'mlp_model_1.pkl'
pickle.dump(mlp, open(filename, 'wb'))

In [48]:
mlp.score(X_test, y_test)

0.5073257536940355

In [49]:
predictions = mlp.predict(X_test)

In [50]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[146538      0      0 ...      0      0      0]
 [ 66838      0      0 ...      0      0      0]
 [ 32417      0      0 ...      0      0      0]
 ...
 [     1      0      0 ...      0      0      0]
 [     1      0      0 ...      0      0      0]
 [     1      0      0 ...      0      0      0]]


In [51]:
print(classification_report(y_test,predictions))

/home/rebecca/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           1       0.51      1.00      0.67    146538
           2       0.00      0.00      0.00     66838
           3       0.00      0.00      0.00     32417
           4       0.00      0.00      0.00     17235
           5       0.00      0.00      0.00      9804
           6       0.00      0.00      0.00      5611
           7       0.00      0.00      0.00      3547
           8       0.00      0.00      0.00      2290
           9       0.00      0.00      0.00      1410
          10       0.00      0.00      0.00       959
          11       0.00      0.00      0.00       665
          12       0.00      0.00      0.00       443
          13       0.00      0.00      0.00       297
          14       0.00      0.00      0.00       205
          15       0.00      0.00      0.00       144
          16       0.00      0.00      0.00       106
          17       0.00      0.00      0.00        71
          18       0.00    

In [55]:
mlp2 = MLPClassifier(hidden_layer_sizes=(10,5), verbose=3)

In [57]:
mlp2.fit(X_train, y_train)

Iteration 1, loss = 2.63765733
Iteration 2, loss = 1.47629496
Iteration 3, loss = 1.46884533
Iteration 4, loss = 1.46667778
Iteration 5, loss = 1.46313820
Iteration 6, loss = 1.46138473
Iteration 7, loss = 1.46035121
Iteration 8, loss = 1.46048141
Iteration 9, loss = 1.46002725
Iteration 10, loss = 1.45992043
Iteration 11, loss = 1.45999382
Iteration 12, loss = 1.45965549
Iteration 13, loss = 1.45987536
Iteration 14, loss = 1.45943217
Iteration 15, loss = 1.45930867
Iteration 16, loss = 1.45915473
Iteration 17, loss = 1.45836225
Iteration 18, loss = 1.45720097
Iteration 19, loss = 1.45715809
Iteration 20, loss = 1.45658178
Iteration 21, loss = 1.45677835
Iteration 22, loss = 1.45627459
Iteration 23, loss = 1.45671946
Iteration 24, loss = 1.45594825
Iteration 25, loss = 1.45581268
Iteration 26, loss = 1.45609079
Iteration 27, loss = 1.45599908
Iteration 28, loss = 1.45542047
Iteration 29, loss = 1.45551428
Iteration 30, loss = 1.45510158
Iteration 31, loss = 1.45361194
Iteration 32, los

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 5), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=3, warm_start=False)

In [58]:
filename = 'mlp_model_2.pkl'
pickle.dump(mlp2, open(filename, 'wb'))

In [59]:
mlp2.score(X_test, y_test)

0.5073257536940355

In [65]:
predictions = mlp2.predict(X_test)
print(classification_report(y_test,predictions))

/home/rebecca/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           1       0.51      1.00      0.67    146538
           2       0.00      0.00      0.00     66838
           3       0.00      0.00      0.00     32417
           4       0.00      0.00      0.00     17235
           5       0.00      0.00      0.00      9804
           6       0.00      0.00      0.00      5611
           7       0.00      0.00      0.00      3547
           8       0.00      0.00      0.00      2290
           9       0.00      0.00      0.00      1410
          10       0.00      0.00      0.00       959
          11       0.00      0.00      0.00       665
          12       0.00      0.00      0.00       443
          13       0.00      0.00      0.00       297
          14       0.00      0.00      0.00       205
          15       0.00      0.00      0.00       144
          16       0.00      0.00      0.00       106
          17       0.00      0.00      0.00        71
          18       0.00    

In [62]:
mlp3 = MLPRegressor(hidden_layer_sizes=(10,5), verbose=3)

In [63]:
mlp3.fit(X_train, y_train)

Iteration 1, loss = 2400.63327841
Iteration 2, loss = 1.86544076
Iteration 3, loss = 1.98440646
Iteration 4, loss = 2.06947360
Iteration 5, loss = 1.91111774
Iteration 6, loss = 2.30315300
Iteration 7, loss = 2.09342067
Iteration 8, loss = 1.87194204
Iteration 9, loss = 1.88380286
Iteration 10, loss = 1.82485433
Iteration 11, loss = 1.83340522
Iteration 12, loss = 1.80221010
Iteration 13, loss = 1.79531356
Iteration 14, loss = 1.80312311
Iteration 15, loss = 1.79192900
Iteration 16, loss = 1.79108654
Iteration 17, loss = 1.78597249
Iteration 18, loss = 1.78371065
Iteration 19, loss = 1.77861450
Iteration 20, loss = 1.77071766
Iteration 21, loss = 1.76669202
Iteration 22, loss = 1.76327526
Iteration 23, loss = 1.76130989
Iteration 24, loss = 1.75995113
Iteration 25, loss = 1.75914125
Iteration 26, loss = 1.75866558
Iteration 27, loss = 1.75744962
Iteration 28, loss = 1.75641920
Iteration 29, loss = 1.75571636
Iteration 30, loss = 1.75410286
Iteration 31, loss = 1.75225933
Iteration 32, 

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(10, 5), learning_rate='constant',
             learning_rate_init=0.001, max_iter=200, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=None, shuffle=True, solver='adam', tol=0.0001,
             validation_fraction=0.1, verbose=3, warm_start=False)

In [64]:
mlp3.score(X_test, y_test)

0.07030668948407381

In [67]:
filename = 'mlp_model_3.pkl'
pickle.dump(mlp3, open(filename, 'wb'))

In [68]:
mlp4 = MLPClassifier(hidden_layer_sizes=(10,5,7), verbose=3)

In [69]:
mlp4.fit(X_train, y_train)

Iteration 1, loss = inf
Iteration 2, loss = 1.46310334
Iteration 3, loss = 1.46125016
Iteration 4, loss = 1.45969324
Iteration 5, loss = 1.45781339
Iteration 6, loss = 1.45839183
Iteration 7, loss = 1.45656542
Iteration 8, loss = 1.45490153
Iteration 9, loss = 1.45299250
Iteration 10, loss = 1.45138370
Iteration 11, loss = 1.45002971
Iteration 12, loss = 1.44862914
Iteration 13, loss = 1.44758050
Iteration 14, loss = 1.44597927
Iteration 15, loss = 1.44454350
Iteration 16, loss = 1.44323162
Iteration 17, loss = 1.44199991
Iteration 18, loss = 1.44115005
Iteration 19, loss = 1.44030096
Iteration 20, loss = 1.43972780
Iteration 21, loss = 1.43931380
Iteration 22, loss = 1.43887893
Iteration 23, loss = 1.43858267
Iteration 24, loss = 1.43828475
Iteration 25, loss = 1.43797850
Iteration 26, loss = 1.43778243
Iteration 27, loss = 1.43755034
Iteration 28, loss = 1.43720857
Iteration 29, loss = 1.43714609
Iteration 30, loss = 1.43679498
Iteration 31, loss = 1.43658784
Iteration 32, loss = 1.4

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 5, 7), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=3, warm_start=False)

In [70]:
mlp4.score(X_test, y_test)

0.5073257536940355

In [72]:
mlp5 = MLPClassifier(hidden_layer_sizes=(12,7,7,5), verbose=3)

In [73]:
mlp5.fit(X_train, y_train)

Iteration 1, loss = 1.81454278
Iteration 2, loss = 1.46018314
Iteration 3, loss = 1.45825017
Iteration 4, loss = 1.45704788
Iteration 5, loss = 1.45575725
Iteration 6, loss = 1.45177442
Iteration 7, loss = 1.43860126
Iteration 8, loss = 1.43413589
Iteration 9, loss = 1.43242907
Iteration 10, loss = 1.43070224
Iteration 11, loss = 1.42933547
Iteration 12, loss = 1.42776737
Iteration 13, loss = 1.42713985
Iteration 14, loss = 1.42603348
Iteration 15, loss = 1.42537318
Iteration 16, loss = 1.42525265
Iteration 17, loss = 1.42417362
Iteration 18, loss = 1.42399008
Iteration 19, loss = 1.42367708
Iteration 20, loss = 1.42306586
Iteration 21, loss = 1.42361200
Iteration 22, loss = 1.42253144
Iteration 23, loss = 1.42243021
Iteration 24, loss = 1.42231419
Iteration 25, loss = 1.42160888
Iteration 26, loss = 1.42168416
Iteration 27, loss = 1.42124255
Iteration 28, loss = 1.42115860
Iteration 29, loss = 1.42073848
Iteration 30, loss = 1.42062544
Iteration 31, loss = 1.41982830
Iteration 32, los

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(12, 7, 7, 5), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=3, warm_start=False)

In [76]:
mlp5.score(X_test, y_test)
filename = 'mlp_model_5.pkl'
pickle.dump(mlp5, open(filename, 'wb'))

In [79]:
#try xgboost
from xgboost import XGBRegressor


# fit model no training data
xgb = XGBRegressor()
xgb.fit(X_train, y_train)

/home/rebecca/anaconda3/lib/python3.6/site-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[20:26:23] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [80]:
xgb.score(X_test, y_test)

0.19218245165892955